paths:
  bronze:
    news_raw: "bronze/news/stock_news_api"
    yfinance_stock_prices_raw: "bronze/yfinance_prices/"
  silver:
    news_sentiment: "silver/news_sentiment_silver"
    stock_prices: "silver/stock_prices_silver"
  gold:
    sentiment_price_daily: "gold/sentiment_prices/daily"
    # ml_price_prediction: "gold/ml/price_prediction"