paths:
  bronze:
    reddit_raw: "bronze/reddit/"
    yfinance_stock_prices_raw: "bronze/yfinance_prices/"
  silver:
    reddit_records_clean: "silver/reddit/records/"
    reddit_scored: "silver/reddit/scored/"
    yfinance_stock_prices_clean: "silver/yfinance_prices/"
  gold:
    reddit_daily_agg: "gold/reddit/sentiment_daily/"
    prices_sent_daily_agg: "gold/sentiment_prices/fact_daily/"